<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:intel-esg="http://www.intel.com/soae/localServices/REST/" xmlns:md="http://www.intel.com/soae/protocolMetadata-2007a.xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://www.intel.com/soae/localService/oauth-revocation/verifyrefreshtoken" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="VerifyRefreshToken" targetNamespace="http://www.intel.com/soae/localService/oauth-revocation/verifyrefreshtoken">
  <wsdl:message name="VerifyRefreshTokenRequest">
    <wsdl:part name="body" type="xsd:anyType"/>
  </wsdl:message>
  <wsdl:message name="VerifyRefreshTokenResponse">
    <wsdl:part name="body" type="xsd:anyType"/>
  </wsdl:message>
  <wsdl:portType name="VerifyRefreshToken">
    <wsdl:operation name="invoke">
      <wsdl:input message="tns:VerifyRefreshTokenRequest"/>
      <wsdl:output message="tns:VerifyRefreshTokenResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="VerifyRefreshTokenBinding" type="tns:VerifyRefreshToken">
    <http:binding verb="POST"/>
    <wsdl:operation name="invoke">
      <http:operation location="/verifyRefreshToken"/>
      <wsdl:input>
        <mime:content part="body" type="application/json"/>
        <intel-esg:parameterMapping/>
      </wsdl:input>
      <wsdl:output>
        <mime:content part="body" type="application/json"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="VerifyRefreshTokenService">
    <wsdl:port binding="tns:VerifyRefreshTokenBinding" name="VerifyRefreshTokenPort">
      <http:address location="http://localhost:8080"/>
    </wsdl:port>
  </wsdl:service>
  <plnk:partnerLinkType name="VerifyRefreshTokenPartnerLinkType">
    <plnk:role name="service" portType="tns:VerifyRefreshToken"/>
  </plnk:partnerLinkType>
</wsdl:definitions>