<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:intel-esg="http://www.intel.com/soae/localServices/REST/" xmlns:md="http://www.intel.com/soae/protocolMetadata-2007a.xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:salesforce="http://www.intel.com/soae/rest/salesforce" xmlns:tns="http://www.intel.com/soae/rest/salesforce/passwordLogin" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Salesforce_Password_Login" targetNamespace="http://www.intel.com/soae/rest/salesforce/passwordLogin">
  <wsdl:message name="Salesforce_Password_LoginRequest">
    <wsdl:part intel-esg:fixed="password" name="grant_type" type="xsd:string"/>
    <wsdl:part name="client_id" type="xsd:string"/>
    <wsdl:part name="client_secret" type="xsd:string"/>
    <wsdl:part name="username" type="xsd:string"/>
    <wsdl:part name="password" type="xsd:string"/>
    <wsdl:part intel-esg:fixed="application/xml" name="accept" type="xsd:anyType" intel-esg:type="md:Header"/>
  </wsdl:message>
  <wsdl:message name="Salesforce_Password_LoginResponse">
    <wsdl:part name="body" type="xsd:anyType" intel-esg:type="salesforce:OAuth"/>
  </wsdl:message>
  <wsdl:portType name="Salesforce_Password_Login">
    <wsdl:operation name="invoke">
      <wsdl:input message="tns:Salesforce_Password_LoginRequest"/>
      <wsdl:output message="tns:Salesforce_Password_LoginResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Salesforce_Password_LoginBinding" type="tns:Salesforce_Password_Login">
    <http:binding verb="POST"/>
    <wsdl:operation name="invoke">
      <http:operation location="/services/oauth2/token"/>
      <wsdl:input>
        <http:urlEncoded/>
        <intel-esg:httpHeaders>
          <intel-esg:header name="accept" part="accept"/>
        </intel-esg:httpHeaders>
        <mime:content type="application/x-www-form-urlencoded"/>
      </wsdl:input>
      <wsdl:output>
        <mime:content part="body" type="application/xml"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Salesforce_Password_LoginService">
    <wsdl:port binding="tns:Salesforce_Password_LoginBinding" name="Salesforce_Password_LoginPort">
      <http:address location="https://login.salesforce.com"/>
    </wsdl:port>
  </wsdl:service>
  <plnk:partnerLinkType name="Salesforce_Password_LoginPartnerLinkType">
    <plnk:role name="service" portType="tns:Salesforce_Password_Login"/>
  </plnk:partnerLinkType>
</wsdl:definitions>