<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:intel-esg="http://www.intel.com/soae/localServices/REST/" xmlns:md="http://www.intel.com/soae/protocolMetadata-2007a.xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://www.intel.com/soae/rest/salesforce/updateRecord" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Salesforce_UpdateRecord" targetNamespace="http://www.intel.com/soae/rest/salesforce/updateRecord">
  <wsdl:message name="Salesforce_UpdateRecordRequest">
    <wsdl:part name="body" type="xsd:anyType" intel-esg:type="xsd:anyType"/>
    <wsdl:part name="record" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="Salesforce_UpdateRecordResponse"/>
  <wsdl:portType name="Salesforce_UpdateRecord">
    <wsdl:operation name="invoke">
      <wsdl:input message="tns:Salesforce_UpdateRecordRequest"/>
      <wsdl:output message="tns:Salesforce_UpdateRecordResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Salesforce_UpdateRecordBinding" type="tns:Salesforce_UpdateRecord">
    <http:binding verb="PATCH"/>
    <wsdl:operation name="invoke">
      <http:operation location="(record)"/>
      <wsdl:input>
        <http:urlReplacement/>
        <mime:content part="body" type="application/xml"/>
      </wsdl:input>
      <wsdl:output/>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Salesforce_UpdateRecordService">
    <wsdl:port binding="tns:Salesforce_UpdateRecordBinding" name="Salesforce_UpdateRecordPort">
      <http:address location="https://na1.salesforce.com"/>
    </wsdl:port>
  </wsdl:service>
  <plnk:partnerLinkType name="Salesforce_UpdateRecordPartnerLinkType">
    <plnk:role name="service" portType="tns:Salesforce_UpdateRecord"/>
  </plnk:partnerLinkType>
</wsdl:definitions>